<div class="destacados tr">
	<div class="destacado td enlace_relacionado">
		<h3 id="destacado_1" class="no_txt">Enlaces relacionados</h3>
		<div class="_content">
			<ul class="list_1">
				<li><a href="http://lacalle13.com"> La Calle 13, sitio oficial </a></li>
				<li><a href="http://lacalle13.com/blog/"> La Calle 13, blog </a></li>
			</ul>
		</div>
	</div>
	<div class="destacado td suscripcion">
		<h3 id="destacado_2" class="no_txt">Suscribete al bolet&iacute;n</h3>
		<div class="_content">
			<p>Envianos un email a lacalle13.net@gmail.com y te agregaremos al
			bolet&iacute;n con las nuevas cosas que vayan saliendo</p>
		</div>
	</div>
	<div class="destacado td last about">
		<h3 id="destacado_3" class="no_txt">&iquest; Por qu&eacute; esta web ?</h3>
		<div class="_content">
			<p>La Calle 13 es uno de los grupos m&aacute;s interesantes que he escuchado en
			mucho tiempo, y un grupo de este calibre necesita una p&aacute;gina para que la
			gente pueda disfrutar de su m&uacute;sica, porque en su web no hay mucha
			cosa <!-- 
			Esta web est&aacute; creada porque realmente no me gusta la web que tiene(la web oficial) La Calle 13. 
			La Calle 13 es un grupo que me gusta por muchos motivos, principalmente por la calidad de la m&uacute;sica
			y el contenido de la letra. Todo esto combinado con la fusion tan enriquesedora que hacen en su musica 
			creo que bien vale hacerle esta web, para que la gente que le gusta su m&uacute;sica pueda disfrutar de ella, ir
			a los conicertos, y comprar su m&uacute;sica. Porque estoy seguro que el que escucha la m&uacute;sica, de La Calle 13, no
			podr&aacute; parar de escucharla.
			--></p>
		</div>
	</div>
</div>